# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160223_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='My Location', max_length=1200),
        ),
    ]
