# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='My Location', max_length=1200),
        ),
    ]
